version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/jfrog/jfrog-client-go
    versions:
    - 0.18.0
    - 0.19.1
    - 0.20.1
    - 0.20.2
    - 0.21.0
    - 0.21.1
    - 0.21.2
